#!/usr/bin/env bash

set -euo pipefail

source "$DOTFILES_PATH/scripts/core/_main.sh"

##? Show the public ip
#?? 1.0.0
##?
##? Usage:
##?    ip

docs::eval "$@"

wget -qO- http://ipecho.net/plain | xargs echo